# Universal CloudCannon Configuration
# Works with both CloudCannon and Netlify

source: hugo-site

paths:
  uploads: static/uploads
  static: static

build:
  command: hugo --gc --minify --config hugo.yaml
  output: public
  environment:
    HUGO_VERSION: 0.129.0
    HUGO_ENV: production
    HUGO_ENVIRONMENT: production

# Simple collections
collections_config:
  pages:
    path: content
    output: true
    url: /[slug]/
    
  blog:
    path: content/blog
    output: true
    url: /blog/[slug]/
    
  data:
    path: data
    output: false

# Basic site settings
timezone: UTC