# Universal CloudCannon Configuration  
# Works with both CloudCannon and Netlify
# Enhanced for theme compatibility

source: hugo-site

build:
  command: hugo --gc --minify
  output: public
  environment:
    HUGO_VERSION: 0.129.0
    HUGO_ENV: production
    HUGO_ENVIRONMENT: production
    HUGO_THEME: bigspring
    HUGO_CACHEDIR: "/tmp/hugo_cache"

paths:
  uploads: static/uploads
  static: static

# Simple collections
collections_config:
  pages:
    path: content
    output: true
    url: /[slug]/
    
  blog:
    path: content/blog
    output: true
    url: /blog/[slug]/
    
  data:
    path: data
    output: false

# Basic site settings
timezone: UTC