# CloudCannon Configuration for Hugo Site
# Executed from repository root

source: hugo-site
output: hugo-site/public

build:
  command: cd hugo-site && hugo --gc --minify
  output: hugo-site/public
  environment:
    HUGO_VERSION: 0.129.0
    HUGO_ENV: production
    HUGO_ENVIRONMENT: production
    HUGO_THEME: bigspring
    HUGO_CACHEDIR: "/tmp/hugo_cache"

# Collections for CloudCannon CMS
collections_config:
  pages:
    path: hugo-site/content
    output: true
    url: /[slug]/
    
  blog:
    path: hugo-site/content/blog
    output: true
    url: /blog/[slug]/
    
  data:
    path: hugo-site/data
    output: false

paths:
  uploads: hugo-site/static/uploads
  static: hugo-site/static

# Basic site settings
timezone: UTC