# Universal CloudCannon Configuration  
# Works with both CloudCannon and Netlify
# Enhanced for theme compatibility

source: hugo-site

paths:
  uploads: hugo-site/static/uploads
  static: hugo-site/static

build:
  command: cd hugo-site && hugo --gc --minify
  output: hugo-site/public
  environment:
    HUGO_VERSION: 0.129.0
    HUGO_ENV: production
    HUGO_ENVIRONMENT: production
    HUGO_THEME: bigspring
    # Fallback configurations
    HUGO_MODULE_REPLACEMENTS: "github.com/themefisher/bigspring-light -> ./themes/bigspring"
    # Additional CloudCannon-specific settings
    HUGO_CACHEDIR: "/tmp/hugo_cache"
    HUGO_RESOURCEDIR: "resources"

# Simple collections
collections_config:
  pages:
    path: content
    output: true
    url: /[slug]/
    
  blog:
    path: content/blog
    output: true
    url: /blog/[slug]/
    
  data:
    path: data
    output: false

# Basic site settings
timezone: UTC