# CloudCannon CMS Configuration for Hugo
# Complete setup for non-developer visual editing

# Site Settings
ssg: hugo
source: .

# Build Configuration for CloudCannon
build:
  command: hugo --gc --minify
  output: public
  environment:
    HUGO_VERSION: 0.129.0
    NODE_VERSION: 18
    HUGO_ENVIRONMENT: production
    TZ: UTC

# Collections - Define what can be edited
collections_config:
  pages:
    path: content
    output: true
    url: /[slug]/
    icon: file_document
    name: Pages
    singular_name: Page
    add_options:
      - name: Add New Page
        icon: add_circle
        href: "#add-page"
    _enabled_editors:
      - visual
      - content
    _inputs:
      title:
        comment: The page title shown in browser tabs
      description:
        comment: SEO description for search engines
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
    
  blog:
    path: content/blog
    output: true
    url: /blog/[slug]/
    icon: article
    name: Blog Posts
    singular_name: Blog Post
    sort:
      key: date
      order: desc
    add_options:
      - name: Add Blog Post
        icon: post_add
        href: "#add-post"
    _enabled_editors:
      - visual
      - content
    _inputs:
      title:
        comment: The blog post title
      date:
        comment: Publication date
      author:
        comment: Post author name
      image:
        comment: Featured image for the post
    schemas:
      default:
        path: .cloudcannon/schemas/blog-post.md

  data:
    path: data
    output: false
    icon: data_object
    name: Data Files
    singular_name: Data File
    _enabled_editors:
      - data

# Input Configuration - User-friendly form fields
_inputs:
  title:
    type: text
    label: Page Title
    placeholder: Enter page title
    comment: This appears in browser tabs and search results
  
  description:
    type: textarea
    label: SEO Description
    placeholder: Brief description for search engines
    comment: 150-160 characters recommended
  
  date:
    type: datetime
    label: Publish Date
    instance_value: now
    comment: When this content should be published
  
  draft:
    type: switch
    label: Draft Mode
    comment: Enable to hide from live site
  
  author:
    type: text
    label: Author Name
    placeholder: John Doe
    comment: Who wrote this content
  
  image:
    type: image
    label: Featured Image
    comment: Main image for this content
    uploads_dir: images
    mime_type: image
  
  body:
    type: markdown
    label: Content
    options:
      bold: true
      italic: true
      link: true
      bulletedlist: true
      numberedlist: true
      blockquote: true
      horizontalrule: true
      heading:
        format: h2
        options:
          - h2
          - h3
          - h4
      image: true
      table: true
      undo: true
      redo: true
  
  layout:
    type: select
    label: Page Layout
    options:
      values:
        - default
        - single
        - page
    comment: Choose the layout template
  
  menu:
    type: object
    label: Menu Settings
    comment: Add this page to navigation menus
    options:
      structures:
        _defaults:
          main:
            weight: 10

# Editor Settings
_editables:
  text:
    bold: true
    italic: true
    link: true
  content:
    blockquote: true
    bold: true
    bulletedlist: true
    code: true
    embed: true
    format: p h2 h3 h4
    horizontalrule: true
    image: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    table: true
    undo: true
    underline: true

# Upload Paths
paths:
  uploads: static/images
  dam_uploads: images
  dam_static: 
    - images
    - documents

# File Settings
_options:
  content:
    uploads_dir: images
    mime_type: image
  image:
    uploads_dir: images
    mime_type: image
    width: 1200
    height: 800
    resize_style: contain
    expandable: true

# Hugo-specific settings
build:
  environment: production

# Global Settings
timezone: America/Los_Angeles

# Site Details for CloudCannon interface
_comments:
  title: The main title that appears in browser tabs
  description: SEO description - keep under 160 characters
  date: When this content was published
  author: The person who wrote this content
  image: Main image for social media sharing

# Navigation structure for CloudCannon sidebar
_structure:
  pages:
    style: list
    icon: file_document
  blog:
    style: calendar
    icon: event_note
  data:
    style: list
    icon: data_object