# Production-ready Hugo Configuration
baseURL = ''  # Will be set by Netlify automatically
languageCode = 'en-us'
title = 'My Hugo Site with Bigspring'
theme = 'bigspring'

# Performance optimizations
enableRobotsTXT = true
enableGitInfo = false
disableKinds = ['taxonomy', 'term']
timeout = '30s'

# Allow raw HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site parameters
[params]
# Basic site info
description = "A modern Hugo website with Bigspring theme"
author = "Your Name"

# Contact information
contact_email = "dan@theonlinepart.com"
contact_phone = "+1 (555) 123-4567"

# Form settings
netlify_forms_enabled = true
form_spam_protection = true
form_honeypot_enabled = true

# SEO Settings
google_analytics = ""  # Add your GA ID when ready
google_tag_manager = ""  # Add your GTM ID when ready

# Social Media
facebook = ""
twitter = ""
linkedin = ""
instagram = ""

# Theme variables
[params.variables]
color_primary = "#0AA8A7"
color_secondary = "#376f92"
font_primary = "Lato:wght@300;400;500;600;700"
font_primary_type = "sans-serif"

# Basic navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 30

[[menu.main]]
name = "Demos"
url = "/demos/"
weight = 40
hasChildren = true

[[menu.main]]
name = "Forms & Maps"
parent = "Demos"
url = "/demos/forms-and-maps/"
weight = 41

[[menu.main]]
name = "Video Embeds"
parent = "Demos"
url = "/demos/video-embeds/"
weight = 42

# Output formats for better SEO
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

# Sitemap configuration
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Minification for production
[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

# Caching
[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"
[caches.getcsv]
dir = ":cacheDir/:project"
maxAge = "10s"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"