name = "Bigspring Light"
license = "MIT"
licenselink = "https://github.com/themefisher/bigspring-light/blob/master/LICENSE"
description = "Bigspring is a responsive, clean and beautiful Hugo theme"
homepage = "https://github.com/themefisher/bigspring-light"
tags = ["business", "agency", "startup", "bootstrap", "responsive"]
features = ["responsive", "bootstrap", "clean"]
min_version = "0.58.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com"