# Service Section Structures

service_standard:
  - label: "Standard Service"
    icon: "business"
    value:
      title: "Professional Service"
      images:
        - "images/service-1.png"
      content: "Comprehensive service description highlighting key benefits and unique value propositions"
      button:
        enable: true
        label: "Learn More"
        link: "/services/"

service_consulting:
  - label: "Consulting Service"
    icon: "psychology"
    value:
      title: "Expert Consulting"
      images:
        - "images/service-2.png"
      content: "Strategic consulting services to optimize your operations and drive sustainable growth"
      button:
        enable: true
        label: "Get Consultation"
        link: "/contact/"

service_development:
  - label: "Development Service"
    icon: "code"
    value:
      title: "Custom Development"
      images:
        - "images/service-3.png"
      content: "Tailored development solutions built to meet your specific business requirements"
      button:
        enable: true
        label: "Start Project"
        link: "/contact/"

service_support:
  - label: "Support Service"
    icon: "support_agent"
    value:
      title: "Premium Support"
      images:
        - "images/service-1.png"
      content: "Dedicated support services ensuring your systems run smoothly 24/7"
      button:
        enable: true
        label: "Get Support"
        link: "/support/"

service_training:
  - label: "Training Service"
    icon: "school"
    value:
      title: "Professional Training"
      images:
        - "images/service-2.png"
      content: "Comprehensive training programs to empower your team with new skills"
      button:
        enable: true
        label: "View Courses"
        link: "/training/"

service_maintenance:
  - label: "Maintenance Service"
    icon: "build"
    value:
      title: "System Maintenance"
      images:
        - "images/service-3.png"
      content: "Proactive maintenance services to keep your systems running at peak performance"
      button:
        enable: true
        label: "Schedule Service"
        link: "/maintenance/"