# Homepage Content Configuration
# This file allows easy editing of homepage sections without touching the code

# Banner/Hero Section
banner:
  enable: true
  title: "Transform Your Business with Our Solutions"
  content: "We provide cutting-edge solutions that help businesses grow, adapt, and thrive in today's competitive market"
  image: "images/banner-art.svg"
  button:
    enable: true
    label: "Get Started Today"
    link: "/contact/"

# Features Section
features:
  enable: true
  title: "Why Choose Our Services"
  subtitle: "We deliver exceptional value through innovative solutions"
  items:
    - name: "Fast Performance"
      icon: "fas fa-tachometer-alt"
      content: "Lightning-fast solutions optimized for maximum performance and efficiency"
    - name: "Secure & Reliable"
      icon: "fas fa-shield-alt"
      content: "Enterprise-grade security with 99.9% uptime and data protection"
    - name: "24/7 Support"
      icon: "fas fa-headset"
      content: "Round-the-clock expert support whenever you need assistance"
    - name: "Easy Integration"
      icon: "fas fa-plug"
      content: "Seamless integration with your existing systems and workflows"
    - name: "Cost Effective"
      icon: "fas fa-dollar-sign"
      content: "Competitive pricing with transparent costs and no hidden fees"
    - name: "Scalable Solutions"
      icon: "fas fa-expand-arrows-alt"
      content: "Solutions that grow with your business and adapt to your needs"

# Services Section
services:
  enable: true
  title: "Our Core Services"
  items:
    - title: "Strategic Consulting"
      image: "images/service-1.png"
      content: "Expert guidance to optimize your business operations and drive sustainable growth through data-driven insights and proven methodologies."
      button:
        enable: true
        label: "Learn More"
        link: "/consulting/"
    - title: "Custom Development"
      image: "images/service-2.png"  
      content: "Tailored software solutions built to meet your specific requirements, ensuring perfect alignment with your business processes and goals."
      button:
        enable: true
        label: "View Portfolio"
        link: "/development/"
    - title: "Support & Maintenance"
      image: "images/service-3.png"
      content: "Comprehensive support services to keep your systems running smoothly, including regular maintenance, updates, and troubleshooting."
      button:
        enable: true
        label: "Get Support"
        link: "/support/"

# Screenshot/Demo Section
demo:
  enable: true
  title: "Experience Our Platform <br> In Action"
  subtitle: "See how our solutions can transform your workflow"
  image: "images/screenshot.svg"

# Call to Action Section
cta:
  enable: true
  title: "Ready to Transform Your Business?"
  content: "Join hundreds of satisfied clients who have achieved remarkable results with our solutions"
  image: "images/cta.svg"
  button:
    enable: true
    label: "Start Your Journey"
    link: "/contact/"

# Testimonials Section
testimonials:
  enable: true
  title: "What Our Clients Say"
  items:
    - quote: "The team delivered exceptional results that exceeded our expectations. Our efficiency improved by 40% in just three months."
      author: "John Smith"
      position: "CEO"
      company: "TechCorp Industries"
      image: "images/testimonials/client-1.jpg"
    - quote: "Outstanding support and innovative solutions. They truly understand business needs and deliver accordingly."
      author: "Sarah Johnson"
      position: "Operations Manager"
      company: "Growth Dynamics"
      image: "images/testimonials/client-2.jpg"
    - quote: "Professional, reliable, and results-driven. The best investment we've made for our digital transformation."
      author: "Michael Chen"
      position: "CTO"
      company: "Innovation Labs"
      image: "images/testimonials/client-3.jpg"

# Statistics Section
statistics:
  enable: true
  title: "Our Track Record Speaks"
  items:
    - number: "500+"
      label: "Happy Clients"
      icon: "fas fa-users"
    - number: "1000+"
      label: "Projects Completed"
      icon: "fas fa-check-circle"
    - number: "99.9%"
      label: "Uptime Guarantee"
      icon: "fas fa-server"
    - number: "24/7"
      label: "Support Available"
      icon: "fas fa-clock"