name: Hugo Build and Deploy (Disabled)

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # We removed submodules
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.129.0'
          extended: true
      
      - name: Build Hugo site
        run: |
          cd hugo-site
          hugo --gc --minify --baseURL="https://thonpa25.github.io/Hugo_app/"
      
      - name: List built files
        run: |
          echo "Built files in hugo-site/public:"
          ls -la hugo-site/public/
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: hugo-public
          path: ./hugo-site/public
          retention-days: 1
  
  trigger-netlify:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && secrets.NETLIFY_BUILD_HOOK != ''
    
    steps:
      - name: Trigger Netlify Build
        run: |
          curl -X POST ${{ secrets.NETLIFY_BUILD_HOOK }}
  
  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-public
          path: ./public
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4